### ISSUE TITLE
tpkutils is not compatible with Python 2.7

### ISSUE THREAD

**Issue by Roxyi** [consbio/tpkutils#13]
Hi,

I just installed tpkutils. In the command line, I typed "tpk export mbtiles test.pk test.mbtiles", and I got this "TypeError: 'uri' is an invalid keyword argument for this function"
![image](https://cloud.githubusercontent.com/assets/8086358/24364299/58a12f96-12e0-11e7-8eab-b5ffae801fd7.png)

**Comment by brendan-ward** [comment]
Looks like a possible `sqlite3` library version issue.  What version of python are you running?  Are you using the stock version of `sqlite3`, or a specific version?

**Comment by Roxyi** [comment]
@brendan-ward My python is 2.7.12 |Anaconda 4.2.0 (64-bit)| and sqlite is 3.17.0, I am new to it so I don't know what is the stock version. I just downloaded the precompiled binaries. Thanks.

**Comment by Roxyi** [comment]
@brendan-ward Thank you!!! YES, it is the version issue. I got this fixed by using Python 3.

**Comment by RuneKyndal** [comment]
hi @Roxyi  I'm having the same python 2.x problems as above.   I have both python 3 and 3.5 installed.
but from the command line  I cant seem to be able to force the use of python3 / 3.5 to work

this is what i have done so far
extracted the tpkutils-0.5.1.tar.gz
ran 
$sudo sudo python setup.py build
$sudo python setup.py install

(this runs python 2.7 i believe and running tpk  works.  but gives your error msg then trying to convert)

if i run the build and install  with pythin3, python3.5 python3.5m commands
$sudo python3.5 setup.py build   +   install

$tpk gives an error


rune@server:~/map$ tpk
Traceback (most recent call last):
  File "/usr/local/bin/tpk", line 11, in <module>
    load_entry_point('tpkutils==0.5.1', 'console_scripts', 'tpk')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/tpkutils-0.5.1-py3.5.egg/tpkutils/cli.py", line 25, in <module>
AttributeError: module 'click' has no attribute 'group'


not sure if I missed a step in the manual install here.  I'm new to python
I also need to do the same and export a map.tpk to a map.mbtiles

any input would be greatly appreciated
thanks

**Comment by RuneKyndal** [comment]
I had same python 2.7 Issue.    and compiling / running TPK with Python3.5 
was giving me this error message
`
root@server:~/map/tpkutils-0.5.1/tpkutils# python3.5 cli.py
Traceback (most recent call last):
  File "cli.py", line 25, in <module>
    @click.group()
AttributeError: module 'click' has no attribute 'group'
`
was a problem with click  had to upgrade
`pip3 install --upgrade --force-reinstall click
`

Rune

**Comment by brendan-ward** [comment]
@RuneKyndal any chance you know the versions of `click` before and now after your upgrade?

I realize now I should have pinned a specific version of `click` in `setup.py`
